# Generated by Django 5.2.7 on 2025-11-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
