# Generated by Django 5.2.7 on 2025-11-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0002_alter_componenttype_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentGff',
        ),
    ]
