# Generated by Django 5.2.7 on 2025-11-03 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula_app', '0003_delete_componentgff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentGff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gff_small', models.FloatField()),
                ('gff_medium', models.FloatField()),
                ('gff_large', models.FloatField()),
                ('gff_rupture', models.FloatField()),
                ('gff_total', models.FloatField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gffs', to='formula_app.componenttype')),
            ],
        ),
    ]
